import AnimatedSection from "@/components/AnimatedSection";
import UnifiedNavigation from "@/components/layout/UnifiedNavigation";
import Footer from "@/components/Footer";

const TermsAndConditionsPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <UnifiedNavigation />

      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 lg:px-8 max-w-4xl">
          <AnimatedSection delay={0}>
            <div className="inline-block px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6">
              <span className="text-sm font-semibold text-primary">Legal</span>
            </div>
          </AnimatedSection>

          <AnimatedSection delay={0.1}>
            <h1 className="text-4xl md:text-5xl font-bold mb-8">Terms & Conditions</h1>
          </AnimatedSection>

          <AnimatedSection delay={0.2}>
            <p className="text-muted-foreground mb-8">Last updated: February 5, 2026</p>
          </AnimatedSection>

          <div className="space-y-8 text-muted-foreground leading-relaxed">
            <AnimatedSection delay={0.25}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  1. Acceptance of Terms
                </h2>
                <p>
                  By accessing and using the website and services provided by Vibe Mind AI Solutions
                  ("we," "our," or "us"), you accept and agree to be bound by these Terms and
                  Conditions. If you do not agree with any part of these terms, you must not use our
                  website or services.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.3}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">2. Services</h2>
                <p className="mb-4">
                  Vibe Mind AI Solutions provides AI-powered software development, consulting, and
                  related technology services. Our services include but are not limited to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Custom AI solution development</li>
                  <li>Legacy system modernization</li>
                  <li>AI SDK and tool development</li>
                  <li>AI-powered web and mobile applications</li>
                  <li>Technology consulting and advisory</li>
                </ul>
                <p className="mt-4">
                  Specific terms for individual projects or engagements will be outlined in separate
                  agreements or statements of work.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.35}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">3. Use of Website</h2>
                <p className="mb-4">
                  You agree to use our website only for lawful purposes and in accordance with these
                  Terms. You agree not to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Use the website in any way that violates applicable laws or regulations</li>
                  <li>
                    Attempt to gain unauthorized access to any part of the website or its systems
                  </li>
                  <li>
                    Use automated tools to scrape, crawl, or extract data from the website without
                    permission
                  </li>
                  <li>Transmit any malicious code, viruses, or harmful content</li>
                  <li>Impersonate any person or entity or misrepresent your affiliation</li>
                  <li>Interfere with or disrupt the website's operation or infrastructure</li>
                </ul>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.4}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  4. AI Chat Assistant
                </h2>
                <p className="mb-4">
                  Our website features an AI-powered chat assistant. By using this feature, you
                  acknowledge that:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    Responses generated by the AI are for informational purposes only and do not
                    constitute professional advice
                  </li>
                  <li>
                    We do not guarantee the accuracy, completeness, or reliability of AI-generated
                    responses
                  </li>
                  <li>
                    You should not share sensitive, confidential, or personal information through
                    the chat
                  </li>
                  <li>
                    Chat interactions may be logged for quality improvement and training purposes
                  </li>
                </ul>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.45}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  5. Intellectual Property
                </h2>
                <p className="mb-4">
                  All content on this website, including but not limited to text, graphics, logos,
                  icons, images, audio clips, software, and code, is the property of Vibe Mind AI
                  Solutions or its content suppliers and is protected by applicable intellectual
                  property laws.
                </p>
                <p>
                  You may not reproduce, distribute, modify, create derivative works of, publicly
                  display, or otherwise use any content from this website without our prior written
                  consent.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.5}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  6. Client Projects and Deliverables
                </h2>
                <p className="mb-4">For client engagements:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    Ownership of deliverables will be defined in the applicable project agreement
                  </li>
                  <li>We retain ownership of pre-existing tools, frameworks, and methodologies</li>
                  <li>
                    Confidential information shared during engagements will be protected under
                    separate NDAs
                  </li>
                  <li>
                    Project timelines and scope are subject to the terms of individual contracts
                  </li>
                </ul>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.55}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  7. Limitation of Liability
                </h2>
                <p className="mb-4">
                  To the fullest extent permitted by law, Vibe Mind AI Solutions shall not be liable
                  for any indirect, incidental, special, consequential, or punitive damages,
                  including but not limited to loss of profits, data, or business opportunities,
                  arising out of or in connection with your use of our website or services.
                </p>
                <p>
                  Our total liability for any claim arising from or related to these Terms shall not
                  exceed the amount you paid us, if any, during the twelve (12) months preceding the
                  claim.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.6}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  8. Disclaimer of Warranties
                </h2>
                <p>
                  Our website and services are provided on an "as is" and "as available" basis
                  without warranties of any kind, either express or implied, including but not
                  limited to implied warranties of merchantability, fitness for a particular
                  purpose, and non-infringement. We do not warrant that the website will be
                  uninterrupted, error-free, or free of harmful components.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.65}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">9. Indemnification</h2>
                <p>
                  You agree to indemnify, defend, and hold harmless Vibe Mind AI Solutions and its
                  officers, directors, employees, and agents from and against any claims,
                  liabilities, damages, losses, and expenses arising out of or in any way connected
                  with your access to or use of the website or services, or your violation of these
                  Terms.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.7}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">10. Payment Terms</h2>
                <p className="mb-4">For paid services and project engagements:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    Payment terms, including amounts, schedules, and milestones, will be specified
                    in the applicable project agreement or statement of work
                  </li>
                  <li>
                    Unless otherwise agreed, invoices are due within thirty (30) days of the invoice
                    date
                  </li>
                  <li>
                    Late payments may incur interest at a rate of 1.5% per month or the maximum rate
                    permitted by law, whichever is lower
                  </li>
                  <li>
                    All fees are exclusive of applicable taxes, which shall be borne by the client
                  </li>
                  <li>
                    We reserve the right to suspend services if payments are overdue by more than
                    fifteen (15) days
                  </li>
                </ul>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.75}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  11. Refund & Cancellation Policy
                </h2>
                <p className="mb-4">Our refund and cancellation terms are as follows:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <span className="text-foreground font-medium">Before project commencement</span>{" "}
                    — Full refund of any advance payment, minus any non-refundable consultation or
                    setup fees as outlined in the agreement
                  </li>
                  <li>
                    <span className="text-foreground font-medium">During active development</span> —
                    Refunds are prorated based on work completed and deliverables accepted up to the
                    date of cancellation
                  </li>
                  <li>
                    <span className="text-foreground font-medium">After delivery</span> — No refunds
                    are provided once deliverables have been accepted by the client
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Cancellation notice</span> —
                    Either party may cancel an engagement with thirty (30) days' written notice,
                    unless a shorter period is specified in the project agreement
                  </li>
                </ul>
                <p className="mt-4">
                  Refund requests must be submitted in writing to{" "}
                  <a
                    href="mailto:info@vibemindsolutions.ai"
                    className="text-primary hover:underline"
                  >
                    info@vibemindsolutions.ai
                  </a>
                  . Approved refunds will be processed within fifteen (15) business days.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.8}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  12. Service Level Commitments
                </h2>
                <p className="mb-4">For ongoing service engagements, we commit to the following:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <span className="text-foreground font-medium">Uptime</span> — We target 99.5%
                    uptime for hosted services and applications, excluding scheduled maintenance
                    windows
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Response times</span> — Critical
                    issues will receive an initial response within four (4) business hours;
                    non-critical issues within one (1) business day
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Scheduled maintenance</span> —
                    Planned downtime will be communicated at least forty-eight (48) hours in advance
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Remedies</span> — If uptime falls
                    below the committed level in any calendar month, clients may be eligible for
                    service credits as defined in the applicable service agreement
                  </li>
                </ul>
                <p className="mt-4">
                  Custom SLAs with specific performance metrics, escalation procedures, and
                  penalties may be negotiated and documented in individual service agreements.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.85}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  13. Dispute Resolution & Arbitration
                </h2>
                <p className="mb-4">
                  In the event of any dispute, controversy, or claim arising out of or relating to
                  these Terms or the breach thereof, the parties agree to the following resolution
                  process:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <span className="text-foreground font-medium">Negotiation</span> — The parties
                    shall first attempt to resolve the dispute through good-faith negotiation within
                    thirty (30) days of written notice
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Mediation</span> — If negotiation
                    fails, the parties shall attempt mediation before a mutually agreed mediator
                  </li>
                  <li>
                    <span className="text-foreground font-medium">Arbitration</span> — If mediation
                    is unsuccessful, the dispute shall be referred to and finally resolved by
                    arbitration in accordance with the Arbitration and Conciliation Act, 1996
                    (India). The arbitration shall be conducted by a sole arbitrator mutually
                    appointed by both parties. The seat of arbitration shall be Kochi, Kerala,
                    India. The language of arbitration shall be English
                  </li>
                </ul>
                <p className="mt-4">
                  The arbitrator's award shall be final and binding on both parties. Each party
                  shall bear its own costs of arbitration unless the arbitrator directs otherwise.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.9}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">14. Governing Law</h2>
                <p>
                  These Terms and Conditions shall be governed by and construed in accordance with
                  the laws of India. Subject to the arbitration clause above, any disputes arising
                  under or in connection with these Terms shall be subject to the exclusive
                  jurisdiction of the courts located in Kerala, India.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={0.95}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  15. Changes to Terms
                </h2>
                <p>
                  We reserve the right to modify these Terms and Conditions at any time. Changes
                  will be effective immediately upon posting to this page. Your continued use of the
                  website after any changes constitutes acceptance of the new Terms. We encourage
                  you to review these Terms periodically.
                </p>
              </section>
            </AnimatedSection>

            <AnimatedSection delay={1.0}>
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">16. Contact Us</h2>
                <p>
                  If you have any questions about these Terms and Conditions, please contact us:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4 mt-4">
                  <li>
                    Email:{" "}
                    <a
                      href="mailto:info@vibemindsolutions.ai"
                      className="text-primary hover:underline"
                    >
                      info@vibemindsolutions.ai
                    </a>
                  </li>
                  <li>
                    Website:{" "}
                    <a href="/contact" className="text-primary hover:underline">
                      Contact Page
                    </a>
                  </li>
                </ul>
              </section>
            </AnimatedSection>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default TermsAndConditionsPage;
